language: csharp
solution: csharp-sdk.sln
before_install:
- sudo apt-get install doxygen
addons:
  apt:
    update: true
before_deploy:
- sh ./script/package.sh
deploy:
  provider: releases
  api_key: 85c848bca12158cc6fd7a3262b64aec6956591bf
  file: LeanCloud-CSharp-SDK.zip
  skip_cleanup: true
  on:
    repo: leancloud/csharp-sdk
    # tags: true
after_deploy:
- doxygen Doxyfile
- sh ./script/deploy.sh
